title = "WF PWR EXTRACT"

[database]
sql_dsn = "SANDPIT"
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"

sql_table_wte = "wf_pwr_wte"
sql_table_kpi = "wf_pwr_kpi"

sql_cooloff = 60

["struct"]
data_dir = "Data"
output_dir = "Output"

["form"]
target_tabs = ["1.WTE", "2.KPI"]